spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-crudwork.cs68ex2aurtb.ap-northeast-1.rds.amazonaws.com:3306/CrudTaskDB
    username: admin
    password: eihuku1111
  sql:
    init:
      mode: always
    
